name: solosafe
description: "The open source GitHub for local and safe payment using block chain technology"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  bip39_mnemonic: ^3.0.7
  web3dart: ^2.7.3
  clipboard: ^0.1.3
  convert: ^3.1.2
  bip39: ^1.0.6
  shared_preferences: ^2.5.2
  bip32: ^2.0.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  package_info_plus: ^8.3.0
  flutter_dotenv: ^5.2.1
  qr_flutter: ^4.1.0
  flutter_blue_plus: ^1.35.3
  device_info_plus: ^11.3.0
  permission_handler: ^11.4.0
  network_info_plus: ^6.1.3
  secure_enclave: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/together.svg




